### PR TITLE
prepublish script added in npm scripts

### PR DESCRIPTION
**Pull request by tarungarg546**
Prepublish script runs every time you try to publish something to npm repository. `prepublish` run before actual publishing.

More Details [here](https://docs.npmjs.com/misc/scripts#common-uses)

:boom:

### CODE REVIEW

**Comment by tarungarg546** [comment]
@ManrajGrover Please Review

**Comment by manrajgrover** [comment]
@tarungarg546 Hey! Apologies. Had been busy with other things. Thanks for pinging and sending this PR. I'll review this tomorrow for sure! :)

**Comment by manrajgrover** [comment]
@tarungarg546 Hey! You have changes in `dist/` which I believe should not be changed. Can you please revert them?

**Comment by tarungarg546** [comment]
Yeah i think i messed git part somewhere checkimg...

**Comment by manrajgrover** [comment]
@tarungarg546 I guess I got it. These must be changes due to previous PR you had sent. I didn't update  `dist` hence the changes shown.

**Comment by tarungarg546** [comment]
So what should we do?
Are you gonna rectify it?

**Comment by manrajgrover** [comment]
I'm merging this. Thank you for contributing! :smile:

**Pull request merged**
